import type { SubscriptionPlan, UserRole } from '../types/user';

export type NavGroup = 'explore' | 'monitor' | 'analyse' | 'work' | 'account' | 'admin';

export interface NavItem {
  id: string;
  label: string;
  href: string;
  /** Lucide icon name, resolved on the client. */
  icon: string;
  group: NavGroup;
  description: string;
  shortcut?: string;
  requiresRole?: UserRole;
  minPlan?: SubscriptionPlan;
  badge?: 'live' | 'ai' | 'beta' | 'new';
}

export const NAV_GROUP_LABEL: Record<NavGroup, string> = {
  explore: 'Explore',
  monitor: 'Monitor',
  analyse: 'Analyse',
  work: 'Workspace',
  account: 'Account',
  admin: 'Administration',
};

export const NAV_ITEMS: readonly NavItem[] = [
  {
    id: 'dashboard',
    label: 'Mission Control',
    href: '/dashboard',
    icon: 'LayoutDashboard',
    group: 'explore',
    description: 'Live planetary overview with alerts, telemetry and AI briefings.',
    shortcut: 'g d',
  },
  {
    id: 'globe',
    label: '3D Globe',
    href: '/globe',
    icon: 'Earth',
    group: 'explore',
    description: 'Immersive digital twin with 40+ data layers at 60 fps.',
    shortcut: 'g g',
    badge: 'live',
  },
  {
    id: 'map',
    label: '2D Map',
    href: '/map',
    icon: 'Map',
    group: 'explore',
    description: 'Planar mission view with live hazards, radar, traffic and infrastructure.',
    shortcut: 'g m',
    badge: 'live',
  },
  {
    id: 'countries',
    label: 'Countries',
    href: '/countries',
    icon: 'Flag',
    group: 'explore',
    description: 'Deep profiles for 250 territories with 30 indicators each.',
    shortcut: 'g c',
  },
  {
    id: 'cities',
    label: 'Cities',
    href: '/cities',
    icon: 'Building2',
    group: 'explore',
    description: 'Urban intelligence for 40,000 cities and metro areas.',
  },
  {
    id: 'timezones',
    label: 'Time Zones',
    href: '/timezones',
    icon: 'Clock',
    group: 'explore',
    description: 'Live world clock, meeting planner and DST tracker.',
  },
  {
    id: 'timeline',
    label: 'Historical Timeline',
    href: '/timeline',
    icon: 'History',
    group: 'explore',
    description: 'Scrub the planet through 50 years of imagery and events.',
    badge: 'beta',
  },
  {
    id: 'weather',
    label: 'Weather',
    href: '/weather',
    icon: 'CloudSun',
    group: 'monitor',
    description: 'Hyperlocal forecasts, radar, alerts and model comparison.',
    shortcut: 'g w',
    badge: 'live',
  },
  {
    id: 'environment',
    label: 'Environment',
    href: '/environment',
    icon: 'Leaf',
    group: 'monitor',
    description: 'Air quality, climate trends and ecosystem health.',
    shortcut: 'g e',
  },
  {
    id: 'hazards',
    label: 'Hazard Monitor',
    href: '/hazards',
    icon: 'TriangleAlert',
    group: 'monitor',
    description: 'Earthquakes, wildfires, volcanoes, floods and cyclones.',
    badge: 'live',
  },
  {
    id: 'flights',
    label: 'Flights',
    href: '/flights',
    icon: 'Plane',
    group: 'monitor',
    description: 'Live ADS-B traffic, airport boards and route analytics.',
    badge: 'live',
  },
  {
    id: 'ships',
    label: 'Ships',
    href: '/ships',
    icon: 'Ship',
    group: 'monitor',
    description: 'AIS vessel tracking, port calls and chokepoint pressure.',
    badge: 'live',
  },
  {
    id: 'space',
    label: 'Space Weather',
    href: '/space',
    icon: 'Satellite',
    group: 'monitor',
    description: 'Satellites, ISS passes, solar activity and aurora forecasts.',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    href: '/analytics',
    icon: 'ChartColumn',
    group: 'analyse',
    description: 'Cross-country indicators, correlations and rankings.',
    shortcut: 'g a',
  },
  {
    id: 'compare',
    label: 'Compare',
    href: '/compare',
    icon: 'GitCompareArrows',
    group: 'analyse',
    description: 'Side-by-side comparison of any places on Earth.',
  },
  {
    id: 'tourism',
    label: 'Tourism',
    href: '/tourism',
    icon: 'TreePalm',
    group: 'analyse',
    description: 'Visitor flows, seasonality and destination scoring.',
  },
  {
    id: 'ai',
    label: 'AI Assistant',
    href: '/ai',
    icon: 'Sparkles',
    group: 'analyse',
    description: 'Context-aware planetary analyst with map control.',
    shortcut: 'g i',
    badge: 'ai',
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/reports',
    icon: 'FileText',
    group: 'work',
    description: 'Generate, schedule and export intelligence briefs.',
    badge: 'ai',
  },
  {
    id: 'workspace',
    label: 'Workspaces',
    href: '/workspace',
    icon: 'Layers',
    group: 'work',
    description: 'Collaborative scenes with annotations and shared layers.',
  },
  {
    id: 'bookmarks',
    label: 'Saved Places',
    href: '/bookmarks',
    icon: 'Bookmark',
    group: 'work',
    description: 'Collections of places, views and areas of interest.',
    shortcut: 'g b',
  },
  {
    id: 'history',
    label: 'History',
    href: '/history',
    icon: 'Clock4',
    group: 'work',
    description: 'Everywhere you have been and everything you asked.',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    href: '/notifications',
    icon: 'Bell',
    group: 'account',
    description: 'Hazard alerts, report completions and system notices.',
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    icon: 'Settings',
    group: 'account',
    description: 'Appearance, units, layers, privacy and integrations.',
    shortcut: 'g s',
  },
  {
    id: 'profile',
    label: 'Profile',
    href: '/profile',
    icon: 'UserRound',
    group: 'account',
    description: 'Identity, security, sessions and connected accounts.',
  },
  {
    id: 'admin',
    label: 'Admin',
    href: '/admin',
    icon: 'ShieldCheck',
    group: 'admin',
    description: 'Users, content, flags, AI logs and system health.',
    requiresRole: 'admin',
  },
] as const;

export const ADMIN_NAV_ITEMS: readonly NavItem[] = [
  {
    id: 'admin-overview',
    label: 'Overview',
    href: '/admin',
    icon: 'Gauge',
    group: 'admin',
    description: 'Platform KPIs and live system health.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-users',
    label: 'Users',
    href: '/admin/users',
    icon: 'Users',
    group: 'admin',
    description: 'Accounts, roles, plans and suspensions.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-countries',
    label: 'Countries',
    href: '/admin/countries',
    icon: 'Flag',
    group: 'admin',
    description: 'Curate country records and indicator overrides.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-cities',
    label: 'Cities',
    href: '/admin/cities',
    icon: 'Building2',
    group: 'admin',
    description: 'Curate city gazetteer entries and metadata.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-reports',
    label: 'Reports',
    href: '/admin/reports',
    icon: 'FileText',
    group: 'admin',
    description: 'Every generated report with cost attribution.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-ai-logs',
    label: 'AI Logs',
    href: '/admin/ai-logs',
    icon: 'Bot',
    group: 'admin',
    description: 'Prompt/response audit trail, tokens and moderation flags.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-analytics',
    label: 'Analytics',
    href: '/admin/analytics',
    icon: 'ChartColumn',
    group: 'admin',
    description: 'Traffic, retention, latency and error budgets.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-flags',
    label: 'Feature Flags',
    href: '/admin/feature-flags',
    icon: 'ToggleRight',
    group: 'admin',
    description: 'Progressive rollout controls per audience.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-notifications',
    label: 'Broadcasts',
    href: '/admin/notifications',
    icon: 'Megaphone',
    group: 'admin',
    description: 'Compose and schedule platform-wide notices.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-api-keys',
    label: 'API Keys',
    href: '/admin/api-keys',
    icon: 'KeyRound',
    group: 'admin',
    description: 'Issue, scope, rotate and revoke machine credentials.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-audit',
    label: 'Activity Log',
    href: '/admin/audit',
    icon: 'ScrollText',
    group: 'admin',
    description: 'Immutable audit trail of privileged actions.',
    requiresRole: 'admin',
  },
  {
    id: 'admin-system',
    label: 'System',
    href: '/admin/system',
    icon: 'ServerCog',
    group: 'admin',
    description: 'Providers, caches, queues and maintenance mode.',
    requiresRole: 'owner',
  },
] as const;
